#!/usr/bin/env python3
"""Build a segment / function map of the unpacked OREGON image.

Real decompilation of a 16-bit segmented DOS program needs a map of which
segments hold code, which hold data, and where the functions are. We recover
that structure from the relocation table without a full disassembler:

  * Every far call is encoded ``9A off16 seg16`` and its ``seg16`` word is
    relocated. So a relocation whose target word sits exactly 3 bytes after a
    ``0x9A`` byte marks a far call, and (off16 : seg16) is a function entry.
    The set of distinct targets is the cross-segment function table.

  * Relocated words that are *not* far-call segment operands are data/segment
    loads (``mov ax,seg`` / ``push seg`` / far ``jmp``). The segment values they
    carry, weighted by frequency, reveal DGROUP and other data groups.

Outputs:
    config/segments.json   machine-readable map
    docs/segment_map.md     human-readable summary

Usage:
    python3 tools/map_segments.py build/OREGON_unpacked.exe
"""
from __future__ import annotations

import json
import struct
import sys
from collections import defaultdict


def load(path):
    d = open(path, "rb").read()
    hdr = struct.unpack("<13H", d[2:28])
    ncrlc, cparhdr = hdr[2], hdr[3]
    e_ip, e_cs, e_ss, e_sp = hdr[9], hdr[10], hdr[6], hdr[7]
    base = cparhdr * 16
    relocs = [struct.unpack("<HH", d[0x1C + i * 4:0x1C + i * 4 + 4]) for i in range(ncrlc)]
    image = d[base:]
    return image, relocs, dict(ip=e_ip, cs=e_cs, ss=e_ss, sp=e_sp)


def build_map(image, relocs):
    funcs = set()                       # (seg, off) far-call targets
    callers = defaultdict(int)          # target_seg -> number of call sites
    data_seg_refs = defaultdict(int)    # seg value -> times loaded as data/seg
    for off, seg in relocs:
        L = seg * 16 + off              # linear address of the relocated word
        if L + 1 >= len(image):
            continue
        target_seg = image[L] | (image[L + 1] << 8)
        if L >= 3 and image[L - 3] == 0x9A:        # far call
            target_off = image[L - 2] | (image[L - 1] << 8)
            funcs.add((target_seg, target_off))
            callers[target_seg] += 1
        else:
            data_seg_refs[target_seg] += 1

    by_seg = defaultdict(list)
    for s, o in funcs:
        by_seg[s].append(o)
    code_segments = []
    for s in sorted(by_seg):
        offs = sorted(by_seg[s])
        # A genuine code segment hosts several functions and/or is called from
        # many sites. Lone singletons are almost always a 0x9A byte inside a
        # string/data region followed by a coincidental segment word.
        confident = len(offs) >= 2 or callers[s] >= 3
        code_segments.append(dict(
            segment=s,
            file_para=s,
            func_count=len(offs),
            call_sites=callers[s],
            entry_min=offs[0],
            entry_max=offs[-1],
            confident=confident,
            entries=offs,
        ))
    data_segments = [
        dict(segment=s, data_refs=c)
        for s, c in sorted(data_seg_refs.items(), key=lambda kv: -kv[1])
    ]
    return code_segments, data_segments, funcs


def main(argv):
    path = argv[1] if len(argv) > 1 else "build/OREGON_unpacked.exe"
    image, relocs, hdr = load(path)
    code_segments, data_segments, funcs = build_map(image, relocs)

    out = dict(
        source=path,
        image_bytes=len(image),
        image_paragraphs=(len(image) + 15) // 16,
        entry=dict(cs=hdr["cs"], ip=hdr["ip"]),
        stack=dict(ss=hdr["ss"], sp=hdr["sp"]),
        relocations=len(relocs),
        function_count=len(funcs),
        code_segments=code_segments,
        data_segments=data_segments[:20],
    )
    json.dump(out, open("config/segments.json", "w", encoding="utf-8"), indent=2)

    lines = []
    lines.append("# OREGON.EXE unpacked — segment & function map\n")
    lines.append(f"_Generated by `tools/map_segments.py` from `{path}`._\n")
    lines.append(f"- image: {len(image):#x} bytes "
                 f"({(len(image)+15)//16:#x} paragraphs)")
    lines.append(f"- entry: `CS:IP = {hdr['cs']:#06x}:{hdr['ip']:#06x}`  "
                 f"stack `SS:SP = {hdr['ss']:#06x}:{hdr['sp']:#06x}`")
    lines.append(f"- relocations: {len(relocs)}")
    lines.append(f"- distinct far-call functions: {len(funcs)}\n")

    confident = [c for c in code_segments if c["confident"]]
    suspect = [c for c in code_segments if not c["confident"]]
    nfunc_conf = sum(c["func_count"] for c in confident)
    lines.append(f"Note: far strings/CONST live in code segments here (e.g. seg "
                 f"`0x1049` opens with a string pool), so a `0x9A` byte in data "
                 f"can masquerade as a far call. Segments below are split by "
                 f"confidence; the {nfunc_conf} functions in confirmed code "
                 f"segments are the reliable set.\n")
    lines.append("## Confirmed code segments (far-call targets)\n")
    lines.append("| segment | file off | functions | call sites | entry range |")
    lines.append("|---------|----------|-----------|------------|-------------|")
    for c in sorted(confident, key=lambda c: -c["func_count"]):
        lines.append(
            f"| `{c['segment']:#06x}` | `{c['segment']*16:#08x}` | "
            f"{c['func_count']} | {c['call_sites']} | "
            f"`{c['entry_min']:#06x}`..`{c['entry_max']:#06x}` |")
    lines.append(f"\n_{len(suspect)} low-confidence singleton targets omitted "
                 f"(likely 0x9A-in-data false positives)._\n")

    lines.append("\n## Top data/segment references (candidate data groups)\n")
    lines.append("| segment | file off | data refs |")
    lines.append("|---------|----------|-----------|")
    for dseg in data_segments[:12]:
        s = dseg["segment"]
        lines.append(f"| `{s:#06x}` | `{s*16:#08x}` | {dseg['data_refs']} |")
    lines.append("")
    open("docs/segment_map.md", "w", encoding="utf-8").write("\n".join(lines))

    print(f"functions={len(funcs)} across {len(code_segments)} code segments; "
          f"{len(data_segments)} distinct data-seg values")
    print("wrote config/segments.json and docs/segment_map.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
